/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Estatisticas;
import Model.EstatisticasDAO;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batman
 */
public class FormPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPedidos
     */
    public FormPedidos(String Idioma, String Pais) {
        initComponents();
        LoadTable();
        Translate(Idioma, Pais);
    }

    public void LoadTable() {
        try {
            EstatisticasDAO eDAO = new EstatisticasDAO();
            List<Estatisticas> lstEstatisticas = eDAO.LoadTablePedidos();
            DefaultTableModel tablemd = (DefaultTableModel) tblPedidos.getModel();
            tablemd.getDataVector().removeAllElements();
            if (lstEstatisticas.size() > 0) {
                for (Estatisticas Est : lstEstatisticas) {
                    tablemd.addRow(new Object[]{Est.getData(), Est.getComanda(), Est.getMesa(), Est.getValor(), Est.getStatus(), Est.getGarcom()});
                }
                tblPedidos.clearSelection();
            }
            tblPedidos.updateUI();
        } catch (Exception ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        lblPedidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DATA", "PEDIDO", "MESA", "VALOR", "STATUS", "GARÇOM"
            }
        ));
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setMinWidth(90);
            tblPedidos.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblPedidos.getColumnModel().getColumn(0).setMaxWidth(90);
            tblPedidos.getColumnModel().getColumn(1).setMinWidth(70);
            tblPedidos.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblPedidos.getColumnModel().getColumn(1).setMaxWidth(70);
            tblPedidos.getColumnModel().getColumn(2).setMinWidth(50);
            tblPedidos.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblPedidos.getColumnModel().getColumn(2).setMaxWidth(50);
            tblPedidos.getColumnModel().getColumn(3).setMinWidth(80);
            tblPedidos.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblPedidos.getColumnModel().getColumn(3).setMaxWidth(80);
            tblPedidos.getColumnModel().getColumn(4).setMinWidth(90);
            tblPedidos.getColumnModel().getColumn(4).setPreferredWidth(90);
            tblPedidos.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, 581, 221));

        lblPedidos.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblPedidos.setForeground(new java.awt.Color(254, 254, 254));
        lblPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedidos.setText("Relação de Pedidos do Dia");
        getContentPane().add(lblPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 3, 593, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -2, 610, 280));

        setBounds(0, 0, 616, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void Translate(String Idioma, String Pais) {
        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela principal
        lblPedidos.setText(propriedades.getString("PedidosDia"));

        tblPedidos.getColumnModel().getColumn(0).setHeaderValue(propriedades.getString("MesaData").toUpperCase());
        tblPedidos.getColumnModel().getColumn(1).setHeaderValue(propriedades.getString("MenuPed").toUpperCase());
        tblPedidos.getColumnModel().getColumn(2).setHeaderValue(propriedades.getString("Table"));
        tblPedidos.getColumnModel().getColumn(3).setHeaderValue(propriedades.getString("Value"));
        tblPedidos.getColumnModel().getColumn(5).setHeaderValue(propriedades.getString("MDIGar").toUpperCase());
        tblPedidos.getTableHeader().repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
