
package Views;

import Model.Mesas;
import Model.MesasDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batman
 */
public class FormCadastro_Mesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroMesa
     */
    DefaultListModel lstModel;
    String Cad_Efe, Erro_add_mesa, form_principal, DESEJA_EXCLUIR, ERRO_AT_TABLE;

    public FormCadastro_Mesa(String Idioma, String Pais) throws Exception {
        lstModel = new DefaultListModel();
        initComponents();
        Load();
        Translate(Idioma, Pais);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNumeroMesa = new javax.swing.JTextField();
        rdBtnNormal = new javax.swing.JRadioButton();
        rdBtnEspecial = new javax.swing.JRadioButton();
        btnAddMesa = new javax.swing.JButton();
        lblCadMesa = new javax.swing.JLabel();
        lblNumMesa = new javax.swing.JLabel();
        lblListaMesa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMesa = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNumeroMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 67, 43));

        buttonGroup1.add(rdBtnNormal);
        rdBtnNormal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        rdBtnNormal.setForeground(new java.awt.Color(248, 241, 241));
        rdBtnNormal.setText("Normal");
        getContentPane().add(rdBtnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, -1));

        buttonGroup1.add(rdBtnEspecial);
        rdBtnEspecial.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        rdBtnEspecial.setForeground(new java.awt.Color(248, 241, 241));
        rdBtnEspecial.setText("Especial");
        getContentPane().add(rdBtnEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 79, 100, -1));

        btnAddMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnAddMesa.setText("Adicionar");
        btnAddMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMesaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 117, -1, -1));

        lblCadMesa.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        lblCadMesa.setForeground(new java.awt.Color(250, 250, 250));
        lblCadMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadMesa.setText("Cadastro de Mesas");
        getContentPane().add(lblCadMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, 380, -1));

        lblNumMesa.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        lblNumMesa.setForeground(new java.awt.Color(250, 250, 250));
        lblNumMesa.setText("Numero da Mesa");
        getContentPane().add(lblNumMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 43));

        lblListaMesa.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        lblListaMesa.setForeground(new java.awt.Color(254, 242, 242));
        lblListaMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaMesa.setText("Lista de Mesas");
        getContentPane().add(lblListaMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 167, 380, 30));

        tblMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COD", "NUMERO", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMesa);
        if (tblMesa.getColumnModel().getColumnCount() > 0) {
            tblMesa.getColumnModel().getColumn(0).setMinWidth(50);
            tblMesa.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblMesa.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 203, 380, 126));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit_remove.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 117, 112, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -2, 410, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMesaActionPerformed
        try {

            //Criando um novo Objeto
            Mesas MESA = new Mesas();
            MesasDAO mDAO = new MesasDAO();

            //Criando o Objeto Mesas
            MESA.setNumero(Integer.parseInt(txtNumeroMesa.getText()));
            if (rdBtnEspecial.isSelected()) {
                MESA.setTipo("Especial");
                rdBtnEspecial.setSelected(false);
            } else {
                MESA.setTipo("Normal");
                rdBtnNormal.setSelected(false);
            }
            MESA.setStatus("VAZIA");
            JOptionPane.showMessageDialog(rootPane, Cad_Efe);
            //Inserindo no Banco o Obj de mesa
            mDAO.addEntity(MESA);
            txtNumeroMesa.setText("");

            Load();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, Erro_add_mesa + "\n" + e.getMessage(),
                    form_principal, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAddMesaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int i = JOptionPane.showConfirmDialog(rootPane, DESEJA_EXCLUIR);
        if (i == 0) {
            try {

                MesasDAO mDAO = new MesasDAO();
                int numero = (int) tblMesa.getValueAt(tblMesa.getSelectedRow(), 0);
                mDAO.remove(numero);
                Load();
                txtNumeroMesa.setText("");

            } catch (Exception ex) {
                Logger.getLogger(FormCadastro_Mesa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesaMouseClicked
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tblMesaMouseClicked

    public void Load() throws SQLException, Exception {

        try {
            MesasDAO mDAO = new MesasDAO();
            List<Mesas> lstMesas = mDAO.getAllEntity();
            DefaultTableModel tablemd = (DefaultTableModel) tblMesa.getModel();
            tablemd.getDataVector().removeAllElements();
            //if exist any User, fill the Jtable
            if (lstMesas.size() > 0) {
                for (Mesas Mesa : lstMesas) {
                    tablemd.addRow(new Object[]{Mesa.getId(), Mesa.getNumero(), Mesa.getTipo()});
                }
                //Cleaning any selection
                tblMesa.clearSelection();
            }
            tblMesa.updateUI();
            limpar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ERRO_AT_TABLE);
        }
    }

    public void limpar() {
        txtNumeroMesa.setText("");
        btnExcluir.setEnabled(false);
    }

    private void Translate(String Idioma, String Pais) {

        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela de cadastro de garçons
        lblCadMesa.setText(propriedades.getString("jCadMesa"));
        lblNumMesa.setText(propriedades.getString("jNumMesa"));
        rdBtnNormal.setText(propriedades.getString("rdNormal"));
        rdBtnEspecial.setText(propriedades.getString("rdEspecial"));
        btnAddMesa.setText(propriedades.getString("AddMesa"));
        btnExcluir.setText(propriedades.getString("ExMesa"));
        lblListaMesa.setText(propriedades.getString("jListaMesa"));

        Cad_Efe = propriedades.getString("table_add");
        Erro_add_mesa = propriedades.getString("table_e");
        form_principal = propriedades.getString("Main_Form");
        DESEJA_EXCLUIR = propriedades.getString("Want_Delete");
        ERRO_AT_TABLE = propriedades.getString("Erro_table");
        
        tblMesa.getColumnModel().getColumn(0).setHeaderValue(propriedades.getString("COD"));
        tblMesa.getColumnModel().getColumn(1).setHeaderValue(propriedades.getString("Number"));
        tblMesa.getColumnModel().getColumn(2).setHeaderValue(propriedades.getString("Type"));
        tblMesa.getTableHeader().repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMesa;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCadMesa;
    private javax.swing.JLabel lblListaMesa;
    private javax.swing.JLabel lblNumMesa;
    private javax.swing.JRadioButton rdBtnEspecial;
    private javax.swing.JRadioButton rdBtnNormal;
    private javax.swing.JTable tblMesa;
    private javax.swing.JTextField txtNumeroMesa;
    // End of variables declaration//GEN-END:variables
}
