package Views;

import Model.Comandas;
import Model.ComandasDAO;
import Model.Mesas;
import Model.MesasDAO;
import Model.Produto_Pedido;
import Model.Produto_PedidoDAO;
import Model.Users;
import Model.UsersDAO;
import Utils.Formats;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batman
 */
public class FormComanda extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroMesa
     */
    DefaultListModel lstModel;
    int iPosicaoMesa;
    int iIDMesa;
    int iPosicaoGarcom;
    int iIDGarcom;
    int iIDComanda;
    Date dataAtual;
    Calendar cale;
    String Idioma = "pt";
    String Pais = "BR";
    String ERRO_TABLE;
    int m_Usuario;

    public FormComanda(String Idi, String pais, int user) throws Exception {
        lstModel = new DefaultListModel();
        cale = Calendar.getInstance();
        initComponents();
        Mesas();
        Garcon();
        Translate(Idi, pais);
        Idioma = Idi;
        Pais = pais;
        m_Usuario = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        btnAbrir = new javax.swing.JButton();
        btnConcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblProdutos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos_Comanda = new javax.swing.JTable();
        btnMais = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblComis = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        lblComanda = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDat = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        ComboMesa = new javax.swing.JComboBox<>();
        lblGarcom = new javax.swing.JLabel();
        ComboGarcom = new javax.swing.JComboBox<>();
        lblCom = new javax.swing.JLabel();
        LblItens = new javax.swing.JLabel();
        lblTCom = new javax.swing.JLabel();
        lblComissao = new javax.swing.JLabel();
        lblEspecial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbrir.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/698913-icon-81-document-add-48.png"))); // NOI18N
        btnAbrir.setText("Nova");
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 326, 98, 90));

        btnConcluir.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/698912-icon-80-document-checked-48.png"))); // NOI18N
        btnConcluir.setText("Concluir");
        btnConcluir.setEnabled(false);
        btnConcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 326, 98, 90));

        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/698910-icon-79-document-cancel-48.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 326, 98, 90));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));

        lblProdutos.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblProdutos.setForeground(new java.awt.Color(254, 247, 247));
        lblProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProdutos.setText("Produtos");

        tblProdutos_Comanda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblProdutos_Comanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COD", "Produto", "Qtde", "Valor"
            }
        ));
        tblProdutos_Comanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutos_ComandaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos_Comanda);
        if (tblProdutos_Comanda.getColumnModel().getColumnCount() > 0) {
            tblProdutos_Comanda.getColumnModel().getColumn(0).setMinWidth(40);
            tblProdutos_Comanda.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblProdutos_Comanda.getColumnModel().getColumn(0).setMaxWidth(40);
            tblProdutos_Comanda.getColumnModel().getColumn(1).setMinWidth(250);
            tblProdutos_Comanda.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblProdutos_Comanda.getColumnModel().getColumn(1).setMaxWidth(250);
            tblProdutos_Comanda.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        btnMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnMais.setEnabled(false);
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        btnMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit_remove.png"))); // NOI18N
        btnMenos.setEnabled(false);
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMais, btnMenos});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMais, btnMenos});

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, 558, -1));

        lblTotal.setBackground(new java.awt.Color(254, 254, 254));
        lblTotal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(253, 251, 251));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 326, 100, 30));

        lblComis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblComis.setForeground(new java.awt.Color(253, 251, 251));
        lblComis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComis.setText("Comissoes");
        getContentPane().add(lblComis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 362, 117, 30));

        lblTot.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTot.setForeground(new java.awt.Color(253, 251, 251));
        lblTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTot.setText("Total Comanda");
        getContentPane().add(lblTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 398, 117, 30));

        lblComanda.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        lblComanda.setForeground(new java.awt.Color(255, 255, 255));
        lblComanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 13, 47, 37));

        lblDate.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(253, 251, 251));
        lblDate.setText("_____-___-___");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 141, 37));

        lblDat.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDat.setForeground(new java.awt.Color(253, 251, 251));
        lblDat.setText("Data");
        getContentPane().add(lblDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 58, 37));

        lblMesa.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        lblMesa.setForeground(new java.awt.Color(255, 250, 250));
        lblMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMesa.setText("Mesa");
        getContentPane().add(lblMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, 105, 37));

        ComboMesa.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        ComboMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMesa.setEnabled(false);
        ComboMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMesaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 99, 235, 37));

        lblGarcom.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        lblGarcom.setForeground(new java.awt.Color(255, 250, 250));
        lblGarcom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGarcom.setText("Garçom");
        getContentPane().add(lblGarcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, 105, 37));

        ComboGarcom.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        ComboGarcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboGarcom.setEnabled(false);
        ComboGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGarcomActionPerformed(evt);
            }
        });
        getContentPane().add(ComboGarcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 56, 440, 37));

        lblCom.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        lblCom.setForeground(new java.awt.Color(255, 250, 250));
        lblCom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCom.setText("Comanda");
        getContentPane().add(lblCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 105, 37));

        LblItens.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblItens.setForeground(new java.awt.Color(253, 251, 251));
        LblItens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblItens.setText("Total Itens");
        getContentPane().add(LblItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 326, 117, 30));

        lblTCom.setBackground(new java.awt.Color(254, 254, 254));
        lblTCom.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTCom.setForeground(new java.awt.Color(253, 251, 251));
        lblTCom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblTCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 398, 100, 30));

        lblComissao.setBackground(new java.awt.Color(254, 254, 254));
        lblComissao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblComissao.setForeground(new java.awt.Color(253, 251, 251));
        lblComissao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblComissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 362, 100, 30));

        lblEspecial.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblEspecial.setForeground(new java.awt.Color(240, 11, 11));
        lblEspecial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 99, 169, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 610, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        ComboGarcom.setEnabled(true);
        dataAtual = Formats.DataAtualSqlDate();
        lblDate.setText(dataAtual.toString());
        btnAbrir.setEnabled(false);
        btnCancelar.setEnabled(true);
        if (m_Usuario != 2) {
            btnConcluir.setEnabled(true);
        }

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed

        try {
            MesasDAO mDAO = new MesasDAO();
            ComandasDAO cDAO = new ComandasDAO();
            cDAO.Status(iIDComanda, "ENCERRADA");
            mDAO.updateEntity(iIDMesa, "VAZIA");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void tblProdutos_ComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutos_ComandaMouseClicked
        btnMenos.setEnabled(true);
        tblProdutos_Comanda.getValueAt(tblProdutos_Comanda.getSelectedRow(), 0);
    }//GEN-LAST:event_tblProdutos_ComandaMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            //Salvar o Processo corrente, adicionando o status de cancelada
            //atriuir 0 e Null para as variáveis
            MesasDAO mDAO = new MesasDAO();
            ComandasDAO cDAO = new ComandasDAO();
            cDAO.Status(iIDComanda, "CANCELADA");
            mDAO.updateEntity(iIDMesa, "VAZIA");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ComboMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMesaActionPerformed
        try {
            MesasDAO mDAO = new MesasDAO();
            if (ComboMesa.getSelectedIndex() > 0) {
                iIDMesa = mDAO.GetId(ComboMesa.getSelectedIndex(), "VAZIA");
                btnMais.setEnabled(true);
                ComboGarcom.setEnabled(false);
                ComboMesa.setEnabled(false);
                lblEspecial.setText(mDAO.Tipo(iIDMesa));
                add();
                lblComanda.setText(String.valueOf(iIDComanda));
                mDAO.updateEntity(iIDMesa, "OCUPADA");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboMesaActionPerformed

    private void ComboGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGarcomActionPerformed
        try {
            UsersDAO mDAO = new UsersDAO();
            if (ComboGarcom.getSelectedIndex() > 0) {
                iIDGarcom = mDAO.GetId(ComboGarcom.getSelectedIndex(), 2);
                ComboMesa.setEnabled(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ComboGarcomActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        try {
            FormProdutos_Pedido ProdPed = new FormProdutos_Pedido(iIDComanda, this, Idioma, Pais);
            ProdPed.show();

        } catch (Exception ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnMaisActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        Produto_PedidoDAO pDAO;
        try {
            pDAO = new Produto_PedidoDAO();
            int id = (int) tblProdutos_Comanda.getValueAt(tblProdutos_Comanda.getSelectedRow(), 0);
            pDAO.remove(id, iIDComanda);
            Load();
            atualiza();
        } catch (SQLException ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FormComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    public void add() throws SQLException, ParseException {
        Comandas com = new Comandas();
        ComandasDAO cDAO = new ComandasDAO();

        com.setId_mesa(iIDMesa);
        com.setId_Garcom(iIDGarcom);
        com.setData(dataAtual);

        iIDComanda = cDAO.addEntity(com);

    }

    public void abrir(int id) throws Exception {
        iIDComanda = id;
        Comandas com = new Comandas();
        ComandasDAO cDAO = new ComandasDAO();
        MesasDAO mDAO = new MesasDAO();
        UsersDAO gDAO = new UsersDAO();

        com = cDAO.getComanda(iIDComanda);

        lblTotal.setText(String.valueOf(com.getTotal()));
        lblComissao.setText(String.valueOf(com.getTotal_Comissao()));
        lblTCom.setText(String.valueOf((com.getTotal()) + (com.getTotal_Comissao())));
        lblComanda.setText(String.valueOf(com.getId()));
        lblDate.setText(String.valueOf(com.getData()));
        ComboMesa.removeAllItems();
        ComboGarcom.removeAllItems();
        iIDMesa = com.getId_mesa();
        iIDGarcom = com.getId_Garcom();
        ComboMesa.addItem(String.valueOf(mDAO.Numero(iIDMesa)));
        ComboGarcom.addItem(gDAO.GetNome(iIDGarcom));

        btnAbrir.setEnabled(false);
        btnCancelar.setEnabled(true);
        if (m_Usuario != 2) {
            btnConcluir.setEnabled(true);
        }
        btnMais.setEnabled(true);

        Load();

    }

    public void atualiza() throws ParseException, SQLException, Exception {

        Comandas com = new Comandas();
        ComandasDAO cDAO = new ComandasDAO();

        com = cDAO.getComanda(iIDComanda);

        lblTotal.setText(String.valueOf(com.getTotal()));
        lblComissao.setText(String.valueOf(com.getTotal_Comissao()));
        lblTCom.setText(String.valueOf((com.getTotal()) + (com.getTotal_Comissao())));

    }

    public void Load() throws SQLException, Exception {

        try {
            Produto_PedidoDAO pDAO = new Produto_PedidoDAO();
            List<Produto_Pedido> lstProdutos = pDAO.getAllEntity(iIDComanda);
            DefaultTableModel tablemd = (DefaultTableModel) tblProdutos_Comanda.getModel();
            tablemd.getDataVector().removeAllElements();
            //if exist any User, fill the Jtable
            if (lstProdutos.size() > 0) {
                for (Produto_Pedido Produtos : lstProdutos) {
                    tablemd.addRow(new Object[]{Produtos.getId(), Produtos.getNome(), Produtos.getQuantidade(), Produtos.getValor()});
                }
                //Cleaning any selection
                tblProdutos_Comanda.clearSelection();
            }
            tblProdutos_Comanda.updateUI();
            //limpar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ERRO_TABLE);
        }
    }

    public void Mesas() throws SQLException, Exception {
        MesasDAO mDAO = new MesasDAO();
        List<Mesas> lstMesas = mDAO.getAllEntityVazias("VAZIA");
        DefaultTableModel tablemd = (DefaultTableModel) tblProdutos_Comanda.getModel();
        tablemd.getDataVector().removeAllElements();
        ComboMesa.removeAllItems();
        ComboMesa.addItem("Selecione");
        if (lstMesas.size() > 0) {
            for (Mesas Mesa : lstMesas) {
                int i = Mesa.getNumero();
                ComboMesa.addItem(String.valueOf(i));
            }
        }
    }

    public void Garcon() throws SQLException, Exception {

        UsersDAO gDAO = new UsersDAO();
        List<Users> lstGarcons = gDAO.getAllGarcons(2);
        DefaultTableModel tablemd = (DefaultTableModel) tblProdutos_Comanda.getModel();
        tablemd.getDataVector().removeAllElements();
        ComboGarcom.removeAllItems();
        ComboGarcom.addItem("Selecione");
        if (lstGarcons.size() > 0) {
            for (Users garc : lstGarcons) {
                ComboGarcom.addItem(garc.getNome());
            }
        }
    }

    private void Translate(String Idioma, String Pais) {

        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela de cadastro de garçons
        lblDat.setText(propriedades.getString("jDataCom"));
        lblGarcom.setText(propriedades.getString("jGarCom"));
        lblMesa.setText(propriedades.getString("jMesaCom"));
        lblProdutos.setText(propriedades.getString("jProdCom"));
        btnAbrir.setText(propriedades.getString("NovaCom"));
        btnCancelar.setText(propriedades.getString("CancelCom"));
        btnConcluir.setText(propriedades.getString("ConCom"));
        LblItens.setText(propriedades.getString("TotItCom"));
        lblComis.setText(propriedades.getString("ComCom"));
        lblTot.setText(propriedades.getString("TotCom"));
        lblCom.setText(propriedades.getString("Order"));

        ERRO_TABLE = propriedades.getString("Erro_table");

        tblProdutos_Comanda.getColumnModel().getColumn(0).setHeaderValue(propriedades.getString("COD"));
        tblProdutos_Comanda.getColumnModel().getColumn(1).setHeaderValue(propriedades.getString("Product"));
        tblProdutos_Comanda.getColumnModel().getColumn(2).setHeaderValue(propriedades.getString("Amount"));
        tblProdutos_Comanda.getColumnModel().getColumn(3).setHeaderValue(propriedades.getString("Value"));
        tblProdutos_Comanda.getTableHeader().repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboGarcom;
    private javax.swing.JComboBox<String> ComboMesa;
    private javax.swing.JLabel LblItens;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblComanda;
    private javax.swing.JLabel lblComis;
    private javax.swing.JLabel lblComissao;
    private javax.swing.JLabel lblDat;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEspecial;
    private javax.swing.JLabel lblGarcom;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblTCom;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProdutos_Comanda;
    // End of variables declaration//GEN-END:variables
}
