package Views;

import Internacionalização.Internacionalizar;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author batman
 */
public class Form_MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    FormLogin log;

    String strCerteza, conected_user;
    public static String User = "";
    String Idioma = "pt";
    String Pais = "BR";
    int m_Usuario;
    Internacionalizar inter = new Internacionalizar();

    public Form_MDI() {
        initComponents();

    }

    public Form_MDI(String Idi, String pais, boolean teste, int entrada) {
        initComponents();

        Idioma = Idi;
        Pais = pais;
        Translate(Idioma, Pais);
        inter.Translate(Idioma, Pais);
        m_Usuario = entrada;

        if (teste) {
            FormUsuarios cad;
            try {
                cad = new FormUsuarios(Idioma, Pais);
                Desktop.add(cad);
                cad.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        switch (entrada) {
            case 0:
                adm();
                break;
            case 1:
                caixa();
                break;
            case 2:
                garcom();
                break;
            default:
                break;
        }
    }

    private void adm() {

    }

    private void caixa() {
        mnCadastro.setVisible(false);
        mnSaldoComissoes.setVisible(false);
        mnSaldoComissoes.setVisible(false);
    }

    private void garcom() {
        MnUsuarios.setVisible(false);
        mnConsultas.setVisible(false);
        mnGarcom.setVisible(false);
        mnSaldoComissoes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        btnComanda = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnComissoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lbleu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnSobre = new javax.swing.JMenuItem();
        mnCadastro = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnGarcom = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        MnUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnNewOrder = new javax.swing.JMenuItem();
        btnDaytable = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        mnSaldoComissoes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(165, 157, 149));
        setResizable(false);

        Desktop.setBackground(new java.awt.Color(63, 27, 32));

        jToolBar2.setBackground(new java.awt.Color(21, 9, 9));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnComanda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnComanda.setForeground(new java.awt.Color(255, 245, 245));
        btnComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/newComanda.png"))); // NOI18N
        btnComanda.setText("Comanda");
        btnComanda.setFocusable(false);
        btnComanda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComanda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnComanda);

        btnMesas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(255, 245, 245));
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/document-open-64.png"))); // NOI18N
        btnMesas.setText("Mesas do Dia");
        btnMesas.setFocusable(false);
        btnMesas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMesas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });
        jToolBar2.add(btnMesas);

        btnComissoes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnComissoes.setForeground(new java.awt.Color(255, 245, 245));
        btnComissoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/File-64.png"))); // NOI18N
        btnComissoes.setText("Comissões");
        btnComissoes.setFocusable(false);
        btnComissoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComissoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComissoesActionPerformed(evt);
            }
        });
        jToolBar2.add(btnComissoes);

        btnSair.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 245, 245));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/system-log-out-64.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar2.add(btnSair);

        Desktop.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 1440, 90);

        lblUser.setBackground(new java.awt.Color(254, 254, 254));
        lblUser.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(254, 254, 254));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/letter580.png"))); // NOI18N
        Desktop.add(lblUser);
        lblUser.setBounds(0, 530, 580, 100);

        lbleu.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lbleu.setForeground(new java.awt.Color(158, 3, 3));
        lbleu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Desktop.add(lbleu);
        lbleu.setBounds(0, 630, 540, 40);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        Desktop.add(jLabel3);
        jLabel3.setBounds(-130, -300, 2050, 1150);

        jMenuBar1.setForeground(java.awt.Color.gray);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/info-icon.png"))); // NOI18N
        jMenu1.setText("Inicio");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout-icon.png"))); // NOI18N
        jMenuItem1.setText("Trocar Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Actions-system-shutdown-icon.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/System-Info-icon.png"))); // NOI18N
        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu1.add(mnSobre);

        jMenuBar1.add(jMenu1);

        mnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.png"))); // NOI18N
        mnCadastro.setText("Cadastros");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Table-icon.png"))); // NOI18N
        jMenuItem6.setText("Mesas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnCadastro.add(jMenuItem6);

        mnGarcom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GARÇOM.png"))); // NOI18N
        mnGarcom.setText("Garçons");
        mnGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGarcomActionPerformed(evt);
            }
        });
        mnCadastro.add(mnGarcom);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bar-code-icon.png"))); // NOI18N
        jMenuItem8.setText("Produtos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnCadastro.add(jMenuItem8);

        MnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Actions-user-group-new-icon.png"))); // NOI18N
        MnUsuarios.setText("Usuarios");
        MnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUsuariosActionPerformed(evt);
            }
        });
        mnCadastro.add(MnUsuarios);

        jMenuBar1.add(mnCadastro);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/order.png"))); // NOI18N
        jMenu3.setText("Pedidos");

        btnNewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new-file-icon.png"))); // NOI18N
        btnNewOrder.setText("Novo Pedido");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });
        jMenu3.add(btnNewOrder);

        btnDaytable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/architecture-interior-28-24.png"))); // NOI18N
        btnDaytable.setText("Mesas do Dia");
        btnDaytable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaytableActionPerformed(evt);
            }
        });
        jMenu3.add(btnDaytable);

        jMenuBar1.add(jMenu3);

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Preview.png"))); // NOI18N
        mnConsultas.setText("Consultas");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/698587-icon-74-document-search-24.png"))); // NOI18N
        jMenuItem9.setText("Pedidos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnConsultas.add(jMenuItem9);

        mnSaldoComissoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aiga_cashier-24.png"))); // NOI18N
        mnSaldoComissoes.setText("Saldo Comissões");
        mnSaldoComissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaldoComissoesActionPerformed(evt);
            }
        });
        mnConsultas.add(mnSaldoComissoes);

        jMenuBar1.add(mnConsultas);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Wheels (1).png"))); // NOI18N
        jMenu5.setText("Opções");

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/settings-24-24.png"))); // NOI18N
        jMenu6.setText("Idioma");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Brazil-Flag-icon.png"))); // NOI18N
        jMenuItem4.setText("Português");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Portugues(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/United-States-Flag-icon.png"))); // NOI18N
        jMenuItem3.setText("Inglês");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingles(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422))
        );

        setSize(new java.awt.Dimension(1310, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        try {
            int buton = JOptionPane.showConfirmDialog(rootPane, strCerteza);

            if (buton == 0) {

                log = new FormLogin();

                this.dispose();
                log.show();
            } else {

            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int i = JOptionPane.showConfirmDialog(rootPane, strCerteza);
        if (i == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FormCadastro_Mesa cad;
        try {
            cad = new FormCadastro_Mesa(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGarcomActionPerformed
        FormCadastro_Garcons cad;
        try {
            cad = new FormCadastro_Garcons(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnGarcomActionPerformed

    private void MnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUsuariosActionPerformed
        FormUsuarios cad;
        try {
            cad = new FormUsuarios(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnUsuariosActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FormCadastro_Produtos cad;
        try {
            cad = new FormCadastro_Produtos(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        FormComanda cad;
        try {
            cad = new FormComanda(Idioma, Pais, m_Usuario);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnDaytableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaytableActionPerformed
        FormMesas cad;
        try {
            cad = new FormMesas(this.Desktop, Idioma, Pais, m_Usuario);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDaytableActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FormPedidos cad;
        try {
            cad = new FormPedidos(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnSaldoComissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaldoComissoesActionPerformed
        FormComissoes cad;
        try {
            cad = new FormComissoes(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnSaldoComissoesActionPerformed

    private void Portugues(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Portugues

        Idioma = "pt";
        Pais = "BR";

        this.Translate(Idioma, Pais);
        inter.Translate(Idioma, Pais);

    }//GEN-LAST:event_Portugues

    private void Ingles(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingles

        Idioma = "en";
        Pais = "US";
        this.Translate(Idioma, Pais);
        inter.Translate(Idioma, Pais);
    }//GEN-LAST:event_Ingles

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        FormSobre cad;
        try {
            cad = new FormSobre(Idioma, Pais);
            Desktop.add(cad);
            cad.setVisible(true);
            Desktop.setComponentZOrder(cad, 0);
            Dimension desktopsize = Desktop.getSize();
            Dimension tblUser = cad.getSize();

            cad.setLocation((desktopsize.width - tblUser.width) / 2, (desktopsize.height - tblUser.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnSobreActionPerformed

    private void btnComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandaActionPerformed
        btnNewOrder.doClick();
    }//GEN-LAST:event_btnComandaActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        btnDaytable.doClick();
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnComissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComissoesActionPerformed

        mnSaldoComissoes.doClick();
    }//GEN-LAST:event_btnComissoesActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        jMenuItem2.doClick();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Translate(String Idioma, String Pais) {

        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela principal
        jMenu1.setText(propriedades.getString("MDIStart"));
        jMenuItem1.setText(propriedades.getString("MDITroca"));
        jMenuItem2.setText(propriedades.getString("MDISair"));
        btnSair.setText(propriedades.getString("MDISair"));
        mnCadastro.setText(propriedades.getString("MDICadastros"));
        jMenuItem6.setText(propriedades.getString("MDIMesas"));
        mnGarcom.setText(propriedades.getString("MDIGar"));
        jMenuItem8.setText(propriedades.getString("MDIProd"));
        MnUsuarios.setText(propriedades.getString("MDIUsers"));
        mnSobre.setText(propriedades.getString("about"));
        jMenuItem9.setText(propriedades.getString("MDIPed"));
        jMenu3.setText(propriedades.getString("MenuPed"));
        btnNewOrder.setText(propriedades.getString("MDINew"));
        mnSaldoComissoes.setText(propriedades.getString("MDISaldo"));
        btnDaytable.setText(propriedades.getString("MesasDia"));
        btnMesas.setText(propriedades.getString("MesasDia"));
        btnComissoes.setText(propriedades.getString("ComCom"));
        jMenu5.setText(propriedades.getString("OpMDI"));
        jMenu6.setText(propriedades.getString("LangMDI"));
        jMenuItem4.setText(propriedades.getString("ptMDI"));
        jMenuItem3.setText(propriedades.getString("enMDI"));
        mnConsultas.setText(propriedades.getString("Search"));

        strCerteza = propriedades.getString("Want_exit");
        conected_user = propriedades.getString("Conected_User");

    }

    public void User(String str) {
        lbleu.setText(conected_user + ": " + str.toUpperCase() + " ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MnUsuarios;
    private javax.swing.JButton btnComanda;
    private javax.swing.JButton btnComissoes;
    private javax.swing.JMenuItem btnDaytable;
    private javax.swing.JButton btnMesas;
    private javax.swing.JMenuItem btnNewOrder;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbleu;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenuItem mnGarcom;
    private javax.swing.JMenuItem mnSaldoComissoes;
    private javax.swing.JMenuItem mnSobre;
    // End of variables declaration//GEN-END:variables
}
