/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Users;
import Model.UsersDAO;
import Utils.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author batman
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Form_MDI mdi;
    FormUsuarios cadi;
    UsersDAO usDAO;
    String Idioma = "pt";
    String Pais = "BR";
    boolean abrir = false;
    int m_usuario;

    protected Connection Conn;
    protected PreparedStatement Sql;

    //para Tradução
    String strWelcome = "Bem Vindo";
    String strCheck = "Verifique Usuário e Senha";
    String strUsuario = "Usuário Não Encontrado!";
    String strSenha = "Senha Incorreta!";
    String strusuarioValido = "Informe um Usuário Válido!";
    String strSenhaValida = "Informe uma Senha Válida!";
    String strConfirmaSair = "Deseja Realmente Sair?";

    public FormLogin() throws SQLException {
        initComponents();
        this.Conn = Conexao.getConn();
        usDAO = new UsersDAO();
        m_usuario = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        psSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        btnEntra = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnIdioma = new javax.swing.JMenu();
        Portugues = new javax.swing.JMenuItem();
        Ingles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(253, 251, 251));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, -1));

        psSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(psSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        lblSenha.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(253, 251, 251));
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        btnEntra.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        btnEntra.setText("Entrar");
        btnEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntraActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, -1));

        btnSair.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        btnSair.setText(" Sair ");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/final.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/resize-img.php.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 320, 330));

        jMenuBar1.setAlignmentX(10.0F);

        mnIdioma.setText("Idioma");
        mnIdioma.setContentAreaFilled(false);
        mnIdioma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnIdioma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnIdioma.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnIdioma.setRolloverEnabled(true);

        Portugues.setText("Português");
        Portugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortuguesActionPerformed(evt);
            }
        });
        mnIdioma.add(Portugues);

        Ingles.setText("Inglês");
        Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InglesActionPerformed(evt);
            }
        });
        mnIdioma.add(Ingles);

        jMenuBar1.add(mnIdioma);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(261, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        int i = JOptionPane.showConfirmDialog(rootPane, strConfirmaSair);
        if (i == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntraActionPerformed

        if ((txtNome.getText().equals("")) || (psSenha.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, strCheck);
            txtNome.requestFocus();
        } else {
            try {

                if (usDAO.isEmptyEntity() == false) {
                    if ((txtNome.getText().equals("admin")) && (psSenha.getText().equals("admin"))) {
                        JOptionPane.showMessageDialog(this, strWelcome);
                        abrir = true;
                        mdi = new Form_MDI(Idioma, Pais, abrir, 2);
                        mdi.User(txtNome.getText());
                        mdi.show();
                        /*cad = new FormCadastro_Usuarios(Idioma, Pais);
                        cad.verifica = true;
                        cad.show();*/
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, strUsuario);
                    }
                } else if (usDAO.SearchEntity(txtNome.getText().toUpperCase()) != null) {
                    Users user = usDAO.Login(txtNome.getText().toUpperCase());
                    if (user.getSenha().equals(String.valueOf(psSenha.getPassword()))) {
                        m_usuario = user.getCargo();
                        JOptionPane.showMessageDialog(this, strWelcome);
                        abrir = false;
                        mdi = new Form_MDI(Idioma, Pais, abrir, m_usuario);
                        mdi.User(txtNome.getText());
                        mdi.show();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, strSenha);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, strUsuario);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnEntraActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == 10) {
            if (txtNome.getText().equals("")) {
                JOptionPane.showMessageDialog(this, strusuarioValido);
                txtNome.requestFocus();
            } else {
                psSenha.requestFocus();
            }

        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void psSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psSenhaKeyPressed
        if (evt.getKeyCode() == 10) {
            if (psSenha.getText().equals("")) {
                JOptionPane.showMessageDialog(this, strSenhaValida);
                psSenha.requestFocus();
            } else {
                btnEntra.doClick();
            }

        }
    }//GEN-LAST:event_psSenhaKeyPressed

    private void PortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortuguesActionPerformed
        Locale BR = new Locale("pt", "BR");
        Locale.setDefault(BR);
        this.translate();
        Idioma = "pt";
        Pais = "BR";
    }//GEN-LAST:event_PortuguesActionPerformed

    private void InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InglesActionPerformed
        Locale.setDefault(Locale.US);
        this.translate();
        Idioma = "en";
        Pais = "US";
    }//GEN-LAST:event_InglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormLogin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void translate() {
        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        lblUsuario.setText(propriedades.getString("User"));
        lblSenha.setText(propriedades.getString("Password"));
        mnIdioma.setText(propriedades.getString("Language"));
        Portugues.setText(propriedades.getString("Portuguese"));
        Ingles.setText(propriedades.getString("English"));
        btnEntra.setText(propriedades.getString("Login"));
        btnSair.setText(propriedades.getString("Exit"));

        strWelcome = propriedades.getString("Welcome"); // "Bem Vindo";
        strCheck = propriedades.getString("Check"); // "Verifique Usuário e Senha";
        strUsuario = propriedades.getString("Usuario"); //"Usuário Não Encontrado!";
        strSenha = propriedades.getString("Senha"); //"Senha Incorreta!";
        strusuarioValido = propriedades.getString("UsuarioValido"); //"Informe um Usuário Válido!";
        strSenhaValida = propriedades.getString("SenhaValida"); // "Informe uma Senha Válida!";
        strConfirmaSair = propriedades.getString("ConfirmExit"); // "Informe uma Senha Válida!";
    }

    /*public Connection Conectar() throws SQLException {
        System.setProperty("jdbc.Drives", driver);

        return con;

    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ingles;
    private javax.swing.JMenuItem Portugues;
    private javax.swing.JButton btnEntra;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu mnIdioma;
    private javax.swing.JPasswordField psSenha;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
