package Views;

import Model.Produtos;
import Model.ProdutosDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batman
 */
public class FormCadastro_Produtos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroMesa
     */
    DefaultListModel lstModel;
    String CAD_EFETUADO, ERRO_ADD_PRODUTO, FORM_PRINC, EXCLUIR, ALTERAR, ERRO_TABLE;

    public FormCadastro_Produtos(String Idioma, String Pais) throws Exception {
        lstModel = new DefaultListModel();
        initComponents();
        Load();
        Translate(Idioma, Pais);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblCadProdutos = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblListaProd = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnAlter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 247, -1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblCadProdutos.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblCadProdutos.setForeground(new java.awt.Color(254, 254, 254));
        lblCadProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadProdutos.setText("Cadastro de Produtos");
        getContentPane().add(lblCadProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 40));

        lblNome.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblNome.setForeground(new java.awt.Color(254, 247, 247));
        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        lblListaProd.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblListaProd.setForeground(new java.awt.Color(254, 254, 254));
        lblListaProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaProd.setText("Lista de Produtos");
        getContentPane().add(lblListaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 168, 380, 30));

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COD", "NOME", "PREÇO"
            }
        ));
        tblProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProd);
        if (tblProd.getColumnModel().getColumnCount() > 0) {
            tblProd.getColumnModel().getColumn(0).setMinWidth(50);
            tblProd.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblProd.getColumnModel().getColumn(0).setMaxWidth(50);
            tblProd.getColumnModel().getColumn(1).setResizable(false);
            tblProd.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblProd.getColumnModel().getColumn(2).setMinWidth(100);
            tblProd.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProd.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 204, 380, 126));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit_remove.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 112, -1));

        lblPreco.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(254, 247, 247));
        lblPreco.setText("Preço");
        getContentPane().add(lblPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 90, -1));
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 90, -1));

        btnAlter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pencilO.png"))); // NOI18N
        btnAlter.setText("Alterar");
        btnAlter.setEnabled(false);
        btnAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 112, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -2, 390, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {

            //Criando um novo Objeto
            Produtos Prod = new Produtos();
            ProdutosDAO pDAO = new ProdutosDAO();

            //Criando o Objeto
            Prod.setNome(txtNome.getText());
            Prod.setPreco(Double.parseDouble(txtPreco.getText()));

            JOptionPane.showMessageDialog(rootPane, CAD_EFETUADO);

            //Inserindo no Banco o Obj
            pDAO.addEntity(Prod);

            Load();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, ERRO_ADD_PRODUTO + "\n" + e.getMessage(),
                    FORM_PRINC, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int i = JOptionPane.showConfirmDialog(rootPane, EXCLUIR);
        if (i == 0) {

            try {

                ProdutosDAO pDAO = new ProdutosDAO();
                int numero = (int) tblProd.getValueAt(tblProd.getSelectedRow(), 0);
                pDAO.remove(numero);
                Load();

            } catch (Exception ex) {
                Logger.getLogger(FormCadastro_Produtos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                Load();
            } catch (Exception ex) {
                Logger.getLogger(FormCadastro_Produtos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdMouseClicked
        btnExcluir.setEnabled(true);
        btnAlter.setEnabled(true);
        btnAdd.setEnabled(false);
        MoverTable(tblProd.getSelectedRow());
        //JOptionPane.showMessageDialog(rootPane, (int) tblShow.getValueAt(tblShow.getSelectedRow(), 0));
    }//GEN-LAST:event_tblProdMouseClicked

    private void btnAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterActionPerformed
        int i = JOptionPane.showConfirmDialog(rootPane, ALTERAR);
        if (i == 0) {
            try {
                ProdutosDAO pDAO = new ProdutosDAO();
                if ((!txtNome.getText().equals("")) && (!txtPreco.getText().equals(""))) {
                    int numero = (int) tblProd.getValueAt(tblProd.getSelectedRow(), 0);
                    pDAO.updateEntity(numero, txtNome.getText(), Double.parseDouble(txtPreco.getText()));
                }
                Load();
            } catch (SQLException ex) {
                Logger.getLogger(FormCadastro_Produtos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FormCadastro_Produtos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                Load();
            } catch (Exception ex) {
                Logger.getLogger(FormCadastro_Produtos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAlterActionPerformed

    public void Load() throws SQLException, Exception {

        try {
            ProdutosDAO pDAO = new ProdutosDAO();
            List<Produtos> lstProdutos = pDAO.getAllEntity();
            DefaultTableModel tablemd = (DefaultTableModel) tblProd.getModel();
            tablemd.getDataVector().removeAllElements();
            //if exist any User, fill the Jtable
            if (lstProdutos.size() > 0) {
                for (Produtos Produtos : lstProdutos) {
                    tablemd.addRow(new Object[]{Produtos.getId(), Produtos.getNome(), Produtos.getPreco()});
                }
                //Cleaning any selection
                tblProd.clearSelection();
            }
            tblProd.updateUI();
            limpar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ERRO_TABLE);
        }
    }

    public void MoverTable(int i) {

        try {
            txtNome.setText(String.valueOf(tblProd.getValueAt(i, 1)));
            txtPreco.setText(String.valueOf(tblProd.getValueAt(i, 2)));
        } catch (Exception e) {

        }

    }

    public void limpar() {
        txtNome.setText("");
        txtPreco.setText("");
        btnExcluir.setEnabled(false);
        btnAlter.setEnabled(false);
        btnAdd.setEnabled(true);

    }

    private void Translate(String Idioma, String Pais) {

        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela de cadastro de garçons
        lblCadProdutos.setText(propriedades.getString("jCadProd"));
        lblNome.setText(propriedades.getString("jProdNome"));
        lblPreco.setText(propriedades.getString("jProdPrice"));
        btnAdd.setText(propriedades.getString("AddProd"));
        btnAlter.setText(propriedades.getString("AlterProd"));
        btnExcluir.setText(propriedades.getString("ExProd"));
        lblListaProd.setText(propriedades.getString("jListaProd"));

        CAD_EFETUADO = propriedades.getString("Prod_add");
        ERRO_ADD_PRODUTO = propriedades.getString("product_error");
        FORM_PRINC = propriedades.getString("Main_Form");
        EXCLUIR = propriedades.getString("Want_Delete");
        ALTERAR = propriedades.getString("Want_alter");
        ERRO_TABLE = propriedades.getString("Erro_table");

        tblProd.getColumnModel().getColumn(0).setHeaderValue(propriedades.getString("COD"));
        tblProd.getColumnModel().getColumn(1).setHeaderValue(propriedades.getString("Name"));
        tblProd.getColumnModel().getColumn(2).setHeaderValue(propriedades.getString("Price"));
        tblProd.getTableHeader().repaint();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlter;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCadProdutos;
    private javax.swing.JLabel lblListaProd;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
