/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Estatisticas;
import Model.EstatisticasDAO;
import Utils.Formats;
import java.sql.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batman
 */
public class FormMesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormMesas
     */
    JDesktopPane Desk;
    Date data;
    int comanda;
    String Idioma = "pt";
    String Pais = "BR";
    int m_Usuario;

    public FormMesas(JDesktopPane desk, String Idi, String pais, int user) {
        initComponents();
        Translate(Idi, pais);
        Idioma = Idi;
        Pais = pais;

        Desk = desk;
        m_Usuario = user;
    }

    public void LoadTable() {
        try {
            EstatisticasDAO eDAO = new EstatisticasDAO();
            List<Estatisticas> lstEstatisticas = eDAO.LoadTableMesas(data);
            DefaultTableModel tablemd = (DefaultTableModel) tblMesas.getModel();
            tablemd.getDataVector().removeAllElements();
            if (lstEstatisticas.size() > 0) {
                for (Estatisticas Est : lstEstatisticas) {
                    tablemd.addRow(new Object[]{Est.getComanda(), Est.getMesa(), Est.getTipo(), Est.getGarcom()});
                }
                tblMesas.clearSelection();
            }
            tblMesas.updateUI();
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        lblComandas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHoje = new javax.swing.JCheckBox();
        btnInformarData = new javax.swing.JCheckBox();
        txtData = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COMANDA", "MESA", "TIPO", "GARÇOM"
            }
        ));
        tblMesas.setAutoscrolls(false);
        tblMesas.setCellSelectionEnabled(true);
        tblMesas.getTableHeader().setResizingAllowed(false);
        tblMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMesas);
        tblMesas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblMesas.getColumnModel().getColumnCount() > 0) {
            tblMesas.getColumnModel().getColumn(0).setMinWidth(90);
            tblMesas.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblMesas.getColumnModel().getColumn(0).setMaxWidth(90);
            tblMesas.getColumnModel().getColumn(1).setMinWidth(70);
            tblMesas.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblMesas.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 131, 382, 304));

        lblComandas.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblComandas.setForeground(new java.awt.Color(254, 254, 254));
        lblComandas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComandas.setText("COMANDAS ABERTAS");
        getContentPane().add(lblComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 382, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar-48.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 37, 61, 56));

        buttonGroup1.add(btnHoje);
        btnHoje.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnHoje.setForeground(new java.awt.Color(253, 251, 251));
        btnHoje.setText("Hoje");
        btnHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHojeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHoje, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 71, 151, -1));

        buttonGroup1.add(btnInformarData);
        btnInformarData.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnInformarData.setForeground(new java.awt.Color(253, 251, 251));
        btnInformarData.setText("Informar Data");
        btnInformarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformarDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnInformarData, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 39, 151, -1));

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setEnabled(false);
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 37, 83, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Preview.png"))); // NOI18N
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 71, 125, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -2, 410, 450));

        setBounds(0, 0, 413, 473);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesasMouseClicked
        FormComanda cad;
        try {
            comanda = (int) tblMesas.getValueAt(tblMesas.getSelectedRow(), 0);
            cad = new FormComanda(Idioma, Pais, m_Usuario);
            Desk.add(cad);
            cad.setVisible(true);
            cad.abrir(comanda);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Form_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMesasMouseClicked

    private void btnInformarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformarDataActionPerformed
        txtData.setEnabled(true);
        txtData.requestFocus();
    }//GEN-LAST:event_btnInformarDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (btnInformarData.isSelected()) {
            if (!txtData.getText().equals("  /  /    ")) {
                data = Formats.StringToDate(txtData.getText());
            }
        } else {
            data = Formats.DataAtualSqlDate();

        }
        LoadTable();
        btnInformarData.setSelected(false);
        btnHoje.setSelected(false);

        txtData.setText("");
        txtData.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHojeActionPerformed
        txtData.setText("");
        txtData.setEnabled(false);
    }//GEN-LAST:event_btnHojeActionPerformed

    private void Translate(String Idioma, String Pais) {

        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela principal
        lblComandas.setText(propriedades.getString("ComAberta"));
        //jLabel2.setText(propriedades.getString("MesaData"));
        btnInformarData.setText(propriedades.getString("InfDataMesa"));
        btnHoje.setText(propriedades.getString("HojeMesa"));
        jButton1.setText(propriedades.getString("ConsMesa"));

        tblMesas.getColumnModel().getColumn(0).setHeaderValue(propriedades.getString("Order"));
        tblMesas.getColumnModel().getColumn(1).setHeaderValue(propriedades.getString("Table"));
        tblMesas.getColumnModel().getColumn(2).setHeaderValue(propriedades.getString("Type"));
        tblMesas.getTableHeader().repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnHoje;
    private javax.swing.JCheckBox btnInformarData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComandas;
    private javax.swing.JTable tblMesas;
    private javax.swing.JFormattedTextField txtData;
    // End of variables declaration//GEN-END:variables
}
