/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Estatisticas;
import Model.EstatisticasDAO;
import Utils.Formats;
import java.sql.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batman
 */
public class FormComissoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormComissoes
     */
    Date entrada;

    public FormComissoes(String Idioma, String Pais) {
        initComponents();
        Translate(Idioma, Pais);
    }

    public void LoadTable() {
        try {
            EstatisticasDAO eDAO = new EstatisticasDAO();
            List<Estatisticas> lstEstatisticas = eDAO.LoadComissoes(entrada);
            DefaultTableModel tablemd = (DefaultTableModel) tblComissoes.getModel();
            tablemd.getDataVector().removeAllElements();
            if (lstEstatisticas.size() > 0) {
                for (Estatisticas Est : lstEstatisticas) {
                    tablemd.addRow(new Object[]{Est.getData(), Est.getGarcom(), Est.getQte_vendas(), Est.getSoma_vendas(), Est.getSoma_comissoes(), Est.getGarcom()});
                }
                tblComissoes.clearSelection();
            }
            tblComissoes.updateUI();
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtData = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("##/##/####");
            txtData = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){

        }
        lblDate = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComissoes = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtData.setEnabled(false);
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 98, -1));

        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar-48.png"))); // NOI18N
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, 73, 60));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Preview.png"))); // NOI18N
        btnSearch.setText("Procurar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 151, -1));

        tblComissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DATA", "GARÇOM", "QTDE", "TOTAL", "COMISSÃO"
            }
        ));
        jScrollPane1.setViewportView(tblComissoes);
        if (tblComissoes.getColumnModel().getColumnCount() > 0) {
            tblComissoes.getColumnModel().getColumn(0).setMinWidth(90);
            tblComissoes.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblComissoes.getColumnModel().getColumn(0).setMaxWidth(90);
            tblComissoes.getColumnModel().getColumn(2).setMinWidth(50);
            tblComissoes.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblComissoes.getColumnModel().getColumn(2).setMaxWidth(50);
            tblComissoes.getColumnModel().getColumn(3).setMinWidth(110);
            tblComissoes.getColumnModel().getColumn(3).setPreferredWidth(110);
            tblComissoes.getColumnModel().getColumn(3).setMaxWidth(110);
            tblComissoes.getColumnModel().getColumn(4).setMinWidth(110);
            tblComissoes.getColumnModel().getColumn(4).setPreferredWidth(110);
            tblComissoes.getColumnModel().getColumn(4).setMaxWidth(110);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 572, 270));

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(254, 247, 247));
        jCheckBox1.setText("Informar Data");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 12, -1, -1));

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(254, 247, 247));
        jCheckBox2.setText("Hoje");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 51, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-21, -42, 680, 520));

        setBounds(0, 0, 580, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (jCheckBox1.isSelected()) {
            if (!txtData.getText().equals("  /  /    ")) {
                entrada = Formats.StringToDate(txtData.getText());
            }
        } else {
            entrada = Formats.DataAtualSqlDate();

        }

        LoadTable();
        
        txtData.setText("");
        txtData.setEnabled(false);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);

        //entrada = Formats.StringToDate(txtData.getText());
        //LoadTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        txtData.setText("");
        txtData.setEnabled(false);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        txtData.setEnabled(true);
        txtData.requestFocus();
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    private void Translate(String Idioma, String Pais) {

        Locale Us = new Locale(Idioma, Pais);
        Locale.setDefault(Us);

        ResourceBundle propriedades = ResourceBundle.getBundle("Internacionalização/appstrings");
        //aqui traduzindo elementos da janela de cadastro de garçons
        //lblDate.setText(propriedades.getString("ComisData"));
        btnSearch.setText(propriedades.getString("ComisSearch"));
        jCheckBox1.setText(propriedades.getString("InfDataMesa"));
        jCheckBox2.setText(propriedades.getString("HojeMesa"));

        tblComissoes.getColumnModel().getColumn(0).setHeaderValue(propriedades.getString("ComisData").toUpperCase());
        tblComissoes.getColumnModel().getColumn(1).setHeaderValue(propriedades.getString("jGarCom").toUpperCase());
        tblComissoes.getColumnModel().getColumn(2).setHeaderValue(propriedades.getString("Amount"));
        tblComissoes.getColumnModel().getColumn(3).setHeaderValue(propriedades.getString("TotProdPed").toUpperCase());
        tblComissoes.getColumnModel().getColumn(4).setHeaderValue(propriedades.getString("ComCom").toUpperCase());
        tblComissoes.getTableHeader().repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblComissoes;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables
}
